# setup monitor (scale 1.6)
#monitor = , preferred, auto, 1.6

# input
input {
    kb_variant = colemak

    # all devices should scroll naturally
    natural_scroll = true
}

# touchpad asus flow
device[asustek-computer-inc.-gz302ea-keyboard-touchpad] {
    enabled = true
}

# variables
#
# Workspaces
$kbMoveWinToWs = Super+Shift


cursor {
  no_hardware_cursors = true
}

# exec

# automatic trackpad on off toggle
exec-once = ~/.local/bin/trackpad-auto.sh

# automount usb sticks
exec-once = thunar --daemon &

# run kdeconnect
exec-once = kdeconnectd
exec-once = kdeconnect-indicator

# make the keyboard static glow in white
exec-once = asusctl aura effect static --colour ffffff

# keybinds

# Trackpad Toggle: Super+N (rechte Ringfinger, Colemak-optimal)
bind = SUPER, N, exec, hyprctl keyword "device[asustek-computer-inc.-gz302ea-keyboard-touchpad]:enabled" false, Trackpad AUS
bindr = SUPER+Shift, N, exec, hyprctl keyword "device[asustek-computer-inc.-gz302ea-keyboard-touchpad]:enabled" true, Trackpad AN

# Globales Layout (bleibt dwindle/master für andere Workspaces)
general {
  layout = dwindle  # oder master, was du bevorzugst
}

# Scrolling Layout Optionen
scrolling {
  fullscreen_on_one_column = true      # Einzelne Spalte nutzt vollen Bildschirm
  column_width = 1.0                   # Spaltenbreite (0.1 - 1.0)
  direction = right                    # Neue Fenster rechts (left/right/up/down)
  follow_focus = true                  # Layout scrollt automatisch zum fokussierten Fenster
}

# Workspace 1 = IMMER auf ASUS Flow (eDP-1)
#workspace = 1, monitor:desc:Tianma Microelectronics Ltd. TL134ADXP03

# Workspaces 2-10 = JEDEM externen Monitor (LG/Garage/Work)
#workspace = 2, monitor:desc:LG Electronics 17MT70 509NZLL087136
#workspace = 3, monitor:desc:LG Electronics 17MT70 509NZLL087136
#workspace = 4, monitor:desc:GIGA-BYTE TECHNOLOGY CO. LTD. M32UC 24270B001826
#workspace = 5, monitor:desc:GIGA-BYTE TECHNOLOGY CO. LTD. M32UC 24270B001826
#workspace = 6, monitor:desc:Samsung Electric Company LS24D60xU HNAX700460
#workspace = 7, monitor:desc:Samsung Electric Company LS24D60xU HNAX700460
#workspace = 8, monitor:desc:Samsung Electric Company LS24D60xU HNAX700460
#workspace = 9, monitor:desc:Samsung Electric Company LS24D60xU HNAX700460
#workspace = 10, monitor:desc:Samsung Electric Company LS24D60xU HNAX700460

# Workspace 5 = Scrolling Layout
workspace = 5, layout:scrolling

# wow
windowrule = float true, match:title World  # FlafyDev/guifetch
# tsm
windowrule = float true, match:class steam_app_402315882  # FlafyDev/guifetch

env = XCURSOR_THEME,Nordzy-cursors
env = XCURSOR_SIZE,24
env = HYPRCURSOR_THEME,Nordzy-cursors
env = HYPRCURSOR_SIZE,24

# load our individual monitor configs
source = ~/.config/ws-monitors/workspaces-current.conf
