# input
input {
    kb_variant = colemak

    touchpad {
        disable_while_typing = $touchpadDisableTyping
        scroll_factor = $touchpadScrollFactor
    }

# all devices should scroll naturally
    natural_scroll = true
}

# touchpad asus flow
device[asustek-computer-inc.-gz302ea-keyboard-touchpad] {
    enabled = true
}

# variables
#
# Workspaces
$kbMoveWinToWs = Super+Shift


# exec

# automatic trackpad on off toggle
exec-once = ~/.local/bin/trackpad-auto.sh

# automount usb sticks
exec-once = thunar --daemon &

# run kdeconnect
exec-once = kdeconnectd
exec-once = kdeconnect-indicator

# make the keyboard static glow in white
exec-once = asusctl aura effect static --colour ffffff

# keybinds

# Trackpad Toggle: Super+N (rechte Ringfinger, Colemak-optimal)
bind = SUPER, N, exec, hyprctl keyword "device[asustek-computer-inc.-gz302ea-keyboard-touchpad]:enabled" false, Trackpad AUS
bindr = SUPER+Shift, N, exec, hyprctl keyword "device[asustek-computer-inc.-gz302ea-keyboard-touchpad]:enabled" true, Trackpad AN

# rules

# wow
windowrule = float true, match:class World  # FlafyDev/guifetch
# tsm
windowrule = float true, match:class TSM|tsm|Trade  # FlafyDev/guifetch

