-- vim.schedule(function ()
  -- local lsp = require "lspconfig"
  -- require("packer").loader("coq_nvim coq.artifacts")
 -- -- local servers = { "pyright", "tsserver", "cssls", "html" }
  -- lsp.pylsp.setup(require("coq")().lsp_ensure_capabilities())
  -- lsp.tsserver.setup(require("coq")().lsp_ensure_capabilities())
  -- lsp.cssls.setup(require("coq")().lsp_ensure_capabilities())
  -- lsp.html.setup(require("coq")().lsp_ensure_capabilities())
  -- -- lsp.dartls.setup(require("coq")().lsp_ensure_capabilities())
  -- lsp.jsonls.setup(require("coq")().lsp_ensure_capabilities())
  -- lsp.svelte.setup(require("coq")().lsp_ensure_capabilities())
-- end)

-- vim.g.coq_settings = { auto_start = true }
